### PR TITLE
Add ability to disable only the visibility button

### PR DESCRIPTION
**Pull request by shawngustaw**

### CODE REVIEW

**Comment by shawngustaw** [comment]
You might have a better idea of a cleaner way to do this but I'd like to be able to disable the visibility button on page load and only enable it after the user has modified the field, so I'm passing this in as a prop: disableButton={!fields[field].dirty}

**Comment by leMaik** [comment]
Looks finde, I don't really see a cleaner way of doing this (using a prop is pretty clean already). Would you mind adding the new prop to the `propTypes`?

**Comment by shawngustaw** [comment]
@leMaik Done :)

**Comment by leMaik** [comment]
@shawngustaw Oh, I forgot to mention the readme. :see_no_evil: I'm sorry…

**Comment by leMaik** [comment]
Btw, this will be released in v1.1.0 (coming in a minute).

**Pull request merged**
