### PR TITLE
Fix margin of visibility button when no label is set

### PR DESCRIPTION
**Pull request by hhaidar**
image

### CODE REVIEW

**Comment by leMaik** [comment]
Thank you very much for the PR! :+1: 
Is the eye still pixel-perfect, i.e. is the distance between the line and the eye the same with and without a label?

**Comment by hhaidar** [comment]
@leMaik it should be now,  I've overlayed two instances and adjusted accordingly

**Comment by leMaik** [comment]
Thank you very much, @hhaidar! I'll publish a new version soon.

**Comment by hhaidar** [comment]
@leMaik wonderful, thank you for being so responsive!

**Comment by leMaik** [comment]
You're welcome. :)
I just released v1.1.3 which includes this fix.

I'll update this component to React v15.5 (`prop-types` package instead of `React.PropTypes` later, so I just want to release v1.1.3 to keep it compatible for now.

**Pull request merged**
